# SITE CONFIGURATION
title: Andrew D'Aoust # your site title
author: Andrew D'Aoust # You :P
description: > # Meta description of Homepage
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://daoust.dev" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Andrew D'Aoust
  links:
    - https://twitter.com/daoustwithaq
    - https://www.facebook.com/andrewdaoust
    - https://www.linkedin.com/in/AndrewDAoust
    - https://plus.google.com/+BenBalter
    - https://github.com/andrewdaoust

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Modern Jekyll theme focused on speed performance &amp; SEO best practices

hero_img: andrew-kellie.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: andrew@daoust.dev # email for form submission

twitter_username: daoustwithaq # replace with your_twitter_username or comment to remove link from footer
github_username:  andrewdaoust # replace with your_github_username or comment to remove link from footer
instagram_username: daoustwithaq # replace with your_instagram_username or comment to remove link from footer

# disqus:
#   shortname: janczizikow # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
# permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
