# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Andrew D'Aoust
email: andrew@daoust.dev
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://daoust.dev" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: daoustwithaq
github_username:  andrewdaoust

# Build settings
markdown: kramdown
theme: texture
plugins:
  - jekyll-feed

texture:
  title: Andrew D'Aoust
  tagline: Data Analytics Engineer
  date_format: "%b %-d, %Y"
  style: black
  showPicker: false
  showNav: true

  social_links:
    twitter: daoustwithaq
    github:  andrewdaoust
    linkedIn: in/andrew-daoust # format: locale/username
    instagram: daoustwithaq

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
- about.md

remote_theme: thelehhman/texture

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
